### ISSUE TITLE
Update node Github wrapper

### ISSUE THREAD

**Issue by g1y** [iFixit/pulldasher#89] opened 2017-08-09 06:50 UTC
#### Problem:
The old github api wrapper doesn't support many new github features that would be really nice to have, such as reviews.

#### Do this:
- Update the wrapper in this repo's `package.json` file to the most up to date one we can manage.
- Find and fix any changed spots in git manager or models that need to be updated.

cc: @copperwall @danielbeardsley @andyg0808 @davidrans

**Comment by danielbeardsley** [comment] 2017-08-09 17:56
Agreed, using a really old version of the library is getting a bit harder.

**Comment by copperwall** [comment] 2017-08-10 18:42
Kind of duplicate issue #79 
This branch is kind of a partial attempt at that. https://github.com/iFixit/pulldasher/tree/update-github-from-pulldasher

**Comment by copperwall** [comment] 2018-05-12 01:58
This is implemented in https://github.com/iFixit/pulldasher/pull/138, but I'm going to close this as a duplicate of #75

**Closed by copperwall** 2018-05-12 01:58 UTC
